#!/bin/sh
export PYTHONPATH=src/:$PYTHONPATH
. venv/bin/activate
pip install -r requirements-analysis.txt -U --pre

echo "Running pycodestyle and pydocstyle"
pycodestyle --ignore=W503 src tests
pydocstyle --ignore=D100,D101,D102,D103,D104,D212,D200,D205,D211,D400 src tests

echo "Running pyflakes"
pyflakes src tests
echo "Running flake8"
flake8 --ignore=W503,H101,H301,H306,H404,H405,M005,C101,C103,S001 src tests
echo "Running pydiatra"
find src tests -name *.py | xargs py2diatra
echo "Running bandit"
bandit -r src
echo "Running bashate"
bashate run run_daemon run_analysis run_tests setup_venv

